# Generated by Django 2.2.10 on 2020-07-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0004_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
