# Generated by Django 2.2.10 on 2020-07-07 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0005_section_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='text',
            new_name='body',
        ),
    ]
