# Generated by Django 2.2.10 on 2020-07-07 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0006_auto_20200707_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationpage',
            name='introduction_header',
        ),
    ]
