# Generated by Django 2.2.10 on 2020-07-07 21:04

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0007_remove_registrationpage_introduction_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
