# Generated by Django 2.2.10 on 2020-07-08 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0009_standardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='introduction',
        ),
    ]
