# Generated by Django 2.2.10 on 2020-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0011_section_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='uploadable',
            field=models.BooleanField(default=False),
        ),
    ]
