# Generated by Django 2.2.10 on 2020-07-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0012_auto_20200711_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='uploadable',
            new_name='upload',
        ),
        migrations.AddField(
            model_name='section',
            name='upload_instruction_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='upload_instruction_title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
