# Generated by Django 2.2.10 on 2020-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0013_auto_20200711_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
