# Generated by Django 2.2.10 on 2020-12-15 21:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('frontend', '0015_auto_20200729_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_people',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='frontend.Person'),
        ),
    ]
