# Generated by Django 2.2.10 on 2020-12-15 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20201215_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Section'),
        ),
    ]
