# Generated by Django 2.2.10 on 2020-12-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20201215_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='section',
            field=models.ManyToManyField(blank=True, to='frontend.Section'),
        ),
    ]
