# Generated by Django 2.2.10 on 2020-12-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20201215_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cv_url',
            field=models.URLField(blank=True),
        ),
    ]
