# Generated by Django 2.2.10 on 2020-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voting_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
