# Generated by Django 2.2.10 on 2020-12-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_question_voting_stopped'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleanswer',
            name='consensus',
            field=models.TextField(blank=True),
        ),
    ]
