# Generated by Django 2.2.10 on 2020-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_possibleanswer_consensus'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibleanswer',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
