# Generated by Django 2.2.10 on 2020-12-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_possibleanswer_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibleanswer',
            options={'ordering': ('ordering',)},
        ),
    ]
