# Generated by Django 2.2.10 on 2020-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20201222_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontoken',
            name='is_chairman',
            field=models.BooleanField(default=False),
        ),
    ]
