# Generated by Django 2.2.10 on 2020-12-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_persontoken_is_chairman'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='next_resolution_launched',
            field=models.BooleanField(default=False),
        ),
    ]
