# Generated by Django 2.2.10 on 2020-12-22 16:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_question_next_resolution_launched'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='consensus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='frontend.PossibleAnswer'),
        ),
        migrations.AddField(
            model_name='question',
            name='stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
