# Generated by Django 2.2.10 on 2020-12-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20201222_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontoken',
            name='questions_to_skip',
            field=models.ManyToManyField(blank=True, to='frontend.Question'),
        ),
    ]
